### ISSUE TITLE
connecting to game api

### ISSUE THREAD

**Issue by nstn8** [Montana-Code-School/jeux#12]
decide on game api.  make basic first connection to boardgame api.  see what info we are getting back.

**Comment by freethewhat** [comment]
Are we planning on using the api to populate our database or have the front end handle this for listing games?

**Comment by nstn8** [comment]
We need to decide which one to use first since there are several.  Id like to make a few calls out them and see what we get back so we can choose the one that best fits our needs.  Once we find one i figured we would populate the database on the backend.  It will be a good learning experience for us and i think that it will be easier to move the games from the master games table to the users game inventory table with out having to fetch it from the api in the middle of that.
