### ISSUE TITLE
Initial Setup with TravisCI

### ISSUE THREAD

**Issue by iverunamok** [Montana-Code-School/jeux#13]
using this documentation: https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo

**Comment by ed42311** [comment]
Gonna open a pull on this?  pick some reviewers, tag them in slack?

**Comment by iverunamok** [comment]
Well, I am still seeing failed and errored tests when I check my https://travis-ci.org/Montana-Code-School/jeux/jobs/333582658... more research is need after 9pm tonight :/

**Comment by freethewhat** [comment]
This issue has been resolved.
