### ISSUE TITLE
Document Project Team

### ISSUE THREAD

**Issue by freethewhat** [Montana-Code-School/jeux#2]

**Comment by freethewhat** [comment]
@nstn8, I've assigned this issue to you since you're the PM and in charge of Roles.

**Comment by nstn8** [comment]
Is this different than what is already in the READ me?  Should i elaborate on everyones roles more?

**Comment by freethewhat** [comment]
Not sure just saw the issue outstanding. I'll let you be the judge if there is enough detail. Feel free to close if you feel everyone's role is clearly defined.

**Comment by freethewhat** [comment]
@nstn8 Are we good to close this out?

**Comment by nstn8** [comment]
yes sir!

**Comment by freethewhat** [comment]
Closing issue
